config/routes.rb
StreamsAdmin::Application.routes.draw do
  
  resources :streams

  root 'streams#new'

end

app/models/stream.rb
class Stream < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
	def index
		@streams = Stream.all
	end
	
	def new
	end

	def create
		@stream = Stream.new(stream_params)

		@stream.save
		redirect_to @stream
	end

	def show
		@stream = Stream.find(params[:id])
	end

	private

		def stream_params
			params.require(:stream).permit(:title, :desc, :date, :time, :url, :streamurl)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreamsAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/streams/index.html.erb
<h1>All streams</h1>

<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Date</th>
		<th>Time</th>
		<th>URL</th>
		<th>Stream URL</th>
	</tr>

  <% @streams.each do |stream| %>
    <tr>
		<td>
			<%= stream.title %>
		</td>
		<td>
			<%= stream.desc %>
		</td>
		<td>
			<%= stream.stream_date %>
		</td>
		<td>
			<%= stream.stream_time %><%= stream.time_zone %>
		</td>
		<td>
			<%= stream.url %>
		</td>
		<td>
			<%= stream.stream_url %>
		</td>      
    </tr>
  <% end %>
</table>

app/views/streams/new.html.erb
<h1>New Stream</h1>

<%= simple_form_for :stream, url: streams_path do |form| %>
	<p>
		<%= form.input :title %>
	</p>
	<p>
		<%= form.text_area :desc, as: :text, label: 'Description' %>
	</p>
	<p>
	
	<div class='input-group date' id='datepicker'>
		<!--input type='text' class="form-control" data-date-format="YYYY/MM/DD" -->
		<%= form.input :stream_date, input_html: { class: 'form-control' } %>
		<span class="input-group-addon">
			<span class="glyphicon glyphicon-calendar"></span>
		</span>
	</div>

	</p>
	<p>
		
	<div class='input-group date' id='timepicker'>
		<%= form.input :stream_time, input_html: { class: 'form-control' } %>
		<span class="input-group-addon">
			<span class="glyphicon glyphicon-calendar"></span>
		</span>
		<%= form.input :time_zone %>
	</div>		
	</p>
	<p>
		<%= form.input :url, as: :url %>
	</p>
	<p>
		<%= form.input :stream_url, as: :url %>
	</p>
	<p>
		<%= form.button :submit, 'Submit', class: 'submit' %>
	</p>
<% end %>

app/views/streams/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @stream.title %>
</p>
<p>
	<strong>Description:</strong>
	<%= @stream.desc %>
</p>
<p>
	<strong>Date:</strong>
	<%= @stream.stream_date %>
</p>
<p>
	<strong>Time:</strong>
	<%= @stream.stream_time %><%= @stream.time_zone %>
</p>
<p>
	<strong>URL:</strong>
	<%= @stream.url %>
</p>
<p>
	<strong>Stream URL:</strong>
	<%= @stream.stream_url %>
</p>